### PR TITLE
Fix initial value in comments of Proposal.status/.executor_result

### PR DESCRIPTION
**Pull request by webmaster128**
hmm, now the ./spec folder gets out of date when I commit such changes from the Web UI.
#trivial

### CODE REVIEW

**Comment by ethanfrey** [comment]
You have to run `make protoc` after updating this to update both the actual auto-generated go protobuf code as well as the spec. The spec is kept in sync with our go code.

I will run `make protoc` and add a commit for you. But it should be easy to do as long as you have docker installed

**Comment by ruseinov** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/iov-one/weave/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ruseinov** [comment]
@webmaster128 please specify #trivial in PR description and re-run travis :)

**Comment by ruseinov** [comment]
@webmaster128 or better yet - I will do it

**Pull request merged**
