### PR TITLE
cmd/bnsd: update transaction attribute names

### LINKED ISSUE #774: Normalize message names
As a developer, I want to define a naming pattern for the protobuf declared messages, so that when exported to a global namespace it is obvious which functionality they belong to.

--- 

Protobuf import does not preserve a namespace. When exposing messages, they are all sharing the same namespace. This is confusing when messages are not descriptive. For example ` multisig.CreateContractMsg create_contract_msg = 56;`

When an extension is imported by an extension, the attribute name must be the same as the type. For example `escrow.ReturnEscrowMsg return_escrow_msg = 54;`

## Acceptance criteria
- [x] define and document the naming pattern for the message protobuf declarations
- [x] apply the above rule to all existing declarations, especially [bnsd declarations](https://github.com/iov-one/weave/blob/master/cmd/bnsd/app/codec.proto)
- [x] update `bnsd` to use type name as attribute names (ie `escrow.CreateEscrowMsg create_escrow_msg = 52;`)

### PR DESCRIPTION
**Pull request by husio**
Update the transaction attribute name to be the same as the message type
they represent.

I did change only one attribute name. Is this enough to close this issue?

resolve #774

### CODE REVIEW

**Comment by iov-bot-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/iov-one/weave/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by husio** [comment]
The CI is failing because it is using an old version of `bnscli`. Why?

**Comment by ethanfrey** [comment]
I think you didn't push something, @husio 

I ran `make test`, which build a new bnscli binary and it failed.

I then ran `make install && make tf` to make it explicitly and it also failed.

Check if you have something locally uncommitted, maybe a .gitignore file?

**Comment by husio** [comment]
I was using an outdated `bnscli` version :angry: This is too error-prone. I need to figure out how to improve this test runner.

**Comment by husio** [comment]
I have rebased all changes to a single commit, because my initial `bnscli` changes were dumb :)

**Comment by ethanfrey** [comment]
> I was using an outdated bnscli version angry This is too error-prone. I need to figure out how to improve this test runner.

Just run `make test` before pushing stuff.
I use `go test ./store/...` to test local changes, but then `make test` locally when pushing a PR

**Pull request merged**
