### PR TITLE
[Spike] Nft spike alex2 - Alternative persistence mode

### PR DESCRIPTION
**Pull request by alpe**
**Do not merge**

See #111
Spike to explore ideas about nft permission and persistence model

### CODE REVIEW

**Comment by ruseinov** [comment]
I like this one more than the previous one, I think it is more straightforward and also next iteration is 
 polished, so easier to understand. 

I would organise Approvals into buckets with action name, just went to re-read @ethanfrey 's spec and saw that this approach is already described [there](https://github.com/iov-one/weave/blob/b2501b67d114b45f97bdbe0adfdd20f7f8f1cf9a/architecture/NFT.md#interfaces). 

Also, do we expect potentially a lot of approvals per action? In this case it might be wise to consider optimising access to user's approvals per action storing an association of key(weave.Address, Action nftSpecies(id)) -> value(index). I'm not sure if an optimisation here is worth it at current stage though.

**Comment by alpe** [comment]
@ruseinov thanks for the feedback. Are you suggesting to put approvals into their own bucket or to use a string type for the action kind? The later makes definitively sense as we may have to separate "base" action types that apply to all nfts and custom action types for a single nft.

**Comment by ruseinov** [comment]
@alpe I'm proposing the approach @ethanfrey suggested in his spec: `[]ApprovalWrapper{action string, approvals []Approval}` . That'd help navigate through the approvals in a more optimised fashion as well as bucketing them further by owner if needed. Yes, in this case action is a string as it is both more readable and easier to maintain, as a string is unique by itself and does not require index, which might accidentally change, as it sometimes happens when adding new constants of the same type. I would prefer string serialisation to int any day of the week, except it takes more memory

**Comment by alpe** [comment]
Closing this now but we keep the branches until approvals are impl.

**Pull request closed without merging**
