### PR TITLE
CHANGELOG.md file created and initialized

### LINKED ISSUE #466: Maintain a CHANGELOG file
> [Don’t let your friends dump git logs into changelogs.](https://keepachangelog.com/en/1.0.0/)

While picking up https://github.com/iov-one/weave/issues/437 I have realized that this will be a breaking change. This must be included in the README compability table later. It should be also included in our release description.

Our [current approach](https://github.com/iov-one/ops/wiki/Release-notes) is to use a tool that generates release notes from commit messages. I believe we can do better.

Unless someone would like to propose a better format, here is an example of a CHANGELOG file

```
## HEAD
- Updated weave.Msg interface to contain Validate method
- Added x/foo package for working with FOO coins
- Removed the use of x/namecoin in cmd/bnsd

## 0.13.1
- Removed x/oldext extension. All code using it was deleted before.
- Added more tests to the x/untested extension

## 0.12.0
- Added foo
```

When making a release, `HEAD` section is renamed to the release number and a new `## HEAD` section is aded.
Changelog update is part of the functionality commit and should be reviewed as part of the changeset.

## Acceptance criteria
- [x] Agree on a changelog file format and update https://github.com/iov-one/ops/wiki/How-do-we-work
- [x] Remove https://github.com/iov-one/ops/wiki/Release-notes
- [x] create a `CHANGELOG.md` file
- [x] backport last ~3~ 2 releases into changelog file

### PR DESCRIPTION
**Pull request by husio**
Bootstrap CHANGELOG.md file that will be manually maintained.

More information at
https://github.com/iov-one/ops/wiki/How-do-we-work#changelog

resolve #466

### CODE REVIEW

**Comment by ruseinov** [comment]
This looks good, except links like #123 don't really work in CHANGELOG.md, so we have to change these to full links if we need them, possible with a shorthand (using link md spec) so that they look exactly the same as now. I will approve this, but would love the links to work.

**Comment by husio** [comment]
I agree that links for each issue number are great functionality. Sadly this is not available for markdown files, because GitHub flavored markdown is not enabled there.
The only two solutions I can think of is 
1. Use explicit linking in markdown `[#123](github.com/...../issue/123)`
2. Manually generate HTML from markdown and substitute `#\d+` with a issue link

Both solutions seems bad as they result in an ugly markdown.

IOV-core does not mention any issues in their changelog. Maybe this is the right approach? https://github.com/iov-one/iov-core/blob/master/CHANGELOG.md

**Comment by ruseinov** [comment]
What you can do is use an explicit link with an alias like (#423)[link] and
that was my suggestion, unless I’m missing something.

**Comment by ruseinov** [comment]
And yes, I think mentioning issues is not actually necessary, changelog should be self-explanatory, but it does not hurt (more work though)

**Comment by husio** [comment]
Let's try without linking issues.

I will remove the `#number` and then please have a look again.

**Pull request merged**
