### PR TITLE
Upgrade tendermint to 0.31.8, fixes socket server cleanup issues

### LINKED ISSUE #851: Close socket on panic()
**Is your feature request related to a problem? Please describe.**
When bnsd failed to start due to incorrect genesis file the unix socket file was still existing and required further clean to restart the app.

**Describe the solution you'd like**
Proper house-keeping would close the socket.

**Describe alternatives you've considered**
Document this behaviour

**Additional context**
Example of a panic stacktrace with v0.18.0:
```
panic: invalid escrow at position: 0 : destination: value is empty

goroutine 33 [running]:
github.com/iov-one/weave/app.(*StoreApp).InitChain(0xc0004d6b40, 0xbc87a66, 0xed4ae801f, 0x0, 0xc0000d54e0, 0x11, 0xc000086300, 0xc0004d8150, 0x1, 0x1, ...)
	/home/travis/gopath/src/github.com/iov-one/weave/app/store.go:317 +0x16d
github.com/tendermint/tendermint/abci/server.(*SocketServer).handleRequest(0xc000196be0, 0xc0004d1bf0, 0xc00006df20)
	/home/travis/gopath/pkg/mod/github.com/tendermint/tendermint@v0.31.5/abci/server/socket_server.go:193 +0x81d
github.com/tendermint/tendermint/abci/server.(*SocketServer).handleRequests(0xc000196be0, 0xc00006de00, 0xf8d8a0, 0xc000096040, 0xc00006df20)
	/home/travis/gopath/pkg/mod/github.com/tendermint/tendermint@v0.31.5/abci/server/socket_server.go:163 +0xe4
created by github.com/tendermint/tendermint/abci/server.(*SocketServer).acceptConnectionsRoutine
	/home/travis/gopath/pkg/mod/github.com/tendermint/tendermint@v0.31.5/abci/server/socket_server.go:119 +0x26a
```

### PR DESCRIPTION
**Pull request by ruseinov**
Fixes #851

### CODE REVIEW

**Comment by ruseinov** [comment]
@alpe yeah. turns out they managed to squeeze in quite a bit of breaking changes between 31.5 and 31.8 :/

**Comment by ruseinov** [comment]
It might actually be a bug, because I haven't found how we should change our code, it looks like it's  the tendermint batch query implementation that breaks it.

**Comment by ruseinov** [comment]
Blocked by https://github.com/tendermint/tendermint/issues/3853

**Comment by husio** [comment]
[Tendermint 0.32.4 was released](https://github.com/tendermint/tendermint/releases/tag/v0.32.4). Is it worth trying with this version?

**Comment by ruseinov** [comment]
AFAIK the client rework is going to be merged only in 0.33, but you can try to get to the bottom of this issue with the client that happens when running tests.

**Comment by alpe** [comment]
Obsolete by #1008

**Pull request closed without merging**
