### PR TITLE
generate docs

### PR DESCRIPTION
**Pull request by ruseinov**
Work on https://github.com/iov-one/weave/issues/187

@ethanfrey I have generared sample docs in html. This plugin does not seem to support RST, so we can probably choose between `.md` and `.html`.

It looks like the easiest way is to generate docs with go proto defs and commit as a developer.
But I think this is not very usable at the moment and it'd be nicer to have a template there too.

### CODE REVIEW

**Comment by ruseinov** [comment]
Also, because it's a protoc plugin - this is not a single file definition, but rather an html per proto def, same as our go definitions.

I'm really not sure how useful that is.

@webmaster128 can you please chip in?

**Comment by webmaster128** [comment]
Yeah nice! Checking this in is good as well.

> and it'd be nicer to have a template there too.

It gives us 80 % of the value with 20 % of the work. This is great stuff.

> This plugin does not seem to support RST, so we can probably choose between `.md` and `.html`.

html is great

> Also, because it's a protoc plugin - this is not a single file definition, but rather an html per proto def, same as our go definitions.

Merging all *.proto files into one document is key since users do not want to try to understand this project's folder structure before using it. The proto files should be merged more or less the same way they are merged in the js codec generation before the html file if generated:

```
find . -name '*.proto' -not -path '*/vendor/*' -not -path '*/examples/*' -not -path '*/cmd/bcpd/*' | sort
```

**Comment by ruseinov** [comment]
@webmaster128 I'm not sure how `find` helps. 
I have tried some things, but ultimately there is a problem with trying to output docs for all the files
```
	protoc -I=. -I=$(GOPATH)/src --doc_out=docs/proto/ --doc_opt=html,index.html `find . -name '*.proto' -not -path '*/vendor/*' -not -path '*/examples/*' -not -path '*/cmd/bcpd/*' | sort | tr '\n' ' ' | sed -e 's/\.\///g' `
```
will complain 
```cmd/bnsd/x/nft/username/codec.proto:9:24: "username.UsernameToken.base" is already defined in file "github.com/iov-one/weave/cmd/bnsd/x/nft/username/codec.proto".```

Because of double imports. It seems to be tricky and I have yet to find a way for this to work.

**Comment by webmaster128** [comment]
> I'm not sure how `find` helps.

In contrast to the existing Makefile, you do not need to maintain a list of folders. But feel free to use any other method to collect all relevant .proto files.

Looks like the system does not understand that

```
cmd/bnsd/x/nft/username/codec.proto
github.com/iov-one/weave/cmd/bnsd/x/nft/username/codec.proto
```

are the same file

**Comment by ruseinov** [comment]
@webmaster128 I have come up with this solution: 
```
	protoc `find . -name '*.proto' -not -path '*/vendor/*' -not -path '*/examples/*' -not -path '*/cmd/bcpd/*' | sort | tr '\n' ' ' | sed  's|\./|-I=|g'`  --doc_out=docs/proto/ --doc_opt=html,index.html `find . -name '*.proto' -not -path '*/vendor/*' -not -path '*/examples/*' -not -path '*/cmd/bcpd/*' | sort | tr '\n' ' '	 | sed -e 's/\.\///g' `

```

But it outputs a pretty empty doc file. I'm not sure if this is worth fighting for to be honest, I'll invest a bit more time though.

**Comment by webmaster128** [comment]
I wonder why this does not happen when we build the .js files from the protos in IOV-Core: https://github.com/iov-one/iov-core/blob/master/packages/iov-bns/package.json#L31
Maybe because no include paths (`-I`) are specified?

**Comment by ruseinov** [comment]
@webmaster128 golang pb generator seems to work differently.
I couldn't make this work using various techniques, so will give it up for now unless somebody has a good solution in mind.

**Comment by webmaster128** [comment]
Couln't re remove all import statements that start with `import "github.com/iov-one/weave`?

Here is a _find and patch_ script for .pro files https://github.com/iov-one/iov-core/blob/master/packages/iov-bns/scripts/cleaned_protos.sh that could be adjusted

**Comment by ruseinov** [comment]
@webmaster128 yeah we could, I'm just not sure that adjusting the files and then generating a doc from this is the best way to approach it, because then the paths don't correspond to whatever is in the app.

Should we define a proper definition of done here first?

**Comment by ethanfrey** [comment]
I will take a look at this today, see if I can combine them somehow.

We need the full paths in the protobuf files for the golang compiler, as it will use that as the import path in `*.pb.go` files , and go needs absolute paths.

I've fought protoc a bit with imports before, I think I might be able to shake this out in within an hour. If not, I would propose multiple html files and do post-processing.

**Comment by ruseinov** [comment]
@ethanfrey take a look at my solution here https://github.com/iov-one/weave/pull/355#issuecomment-467386164 , it kind of works, but generates an empty doc (only base types) and also throws and error 
```[libprotobuf WARNING google/protobuf/compiler/parser.cc:562] No syntax specified for the proto file: . Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)``` which comes from some vendored dirs it seems.

**Comment by ethanfrey** [comment]
Okay, I ran `make prototools` to set up the needed tools, then

`protoc --doc_out=docs/proto/ --doc_opt=html,cash.html --gogofaster_out=. cash/*.proto` to build sample docs (from `make protoc`)

The output looks nice, but my first reaction (besides many small files) is that the links are broken, for example `docs/proto/cash.html` has a link to `x.Coin` that doesn't do anything.

I will try to see what I can build

**Comment by ethanfrey** [comment]
Okay, simple case of getting x.Coin and cash.FeeInfo, cash.SendMsg all in one doc...

`protoc -I=. --doc_out=docs/proto/ --doc_opt=html,cash.html x/cash/*.proto x/*.proto`

Of course, I had to edit x/cash/codec.proto first to change the import:
`import "github.com/iov-one/weave/x/codec.proto";` -> `import "x/codec.proto";`

But then, 
`protoc -I=. --gogofaster_out=. x/cash/*.proto` is broken, with the following import:

`import x "x"`

**Comment by ethanfrey** [comment]
I think inspiration can be taken from https://github.com/iov-one/iov-core/blob/master/packages/iov-bns/scripts/cleaned_protos.sh

**Comment by ethanfrey** [comment]
I had to clean up the `protoc` step, there were lots of errors about not importing gogoprotobuf... it seems it was in your GOPATH, and that was being used, not the one in vendor, which is locked. Also, one regenerating there were significant diffs, as there is a different template used from the your local copy of gogoprotobuf and the one in vendor (not sure which is newer).

Anyway, now always run from vendor for more reproduceable build

**Comment by ethanfrey** [comment]
@webmaster128 Now built in a single-file, hopefully this is what you were looking for.

```
curl https://raw.githubusercontent.com/iov-one/weave/feature/proto-docs/docs/proto/index.html > index.html
open index.html
```

Let me know if this is better. Then there needs to be a build step

**Comment by ruseinov** [comment]
@ethanfrey yeah, it might have actually been an executable problem, glad that this is cleaned up now. looks good to me

**Comment by webmaster128** [comment]
Beautiful 😍 😍 😍

**Pull request merged**
