### PR TITLE
Add RequiredFee field to Check/DeliverResult

### PR DESCRIPTION
**Pull request by ethanfrey**
Addresses #349 

This just adds the fields, must be rebased once #348 is closed and then enforce the required fee in the DynamicFeeHandler.

First pass, to add `x.Coin` to the `weave.DeliverResult` creates an import cycle. weave -> x -> weave

This repo was designed that modules only import from their parent modules to avoid cycles, and that we use interfaces defined in the top level rather than reference implementations from sibling modules. There are two main exceptions, `errors` and `crypto`, which are generic libraries and can be imported by any package, in addition to `weave` itself.

Anyway, if we now add `Coin` to a project-wide interface, I see three options:

* Move coin and coins and related code from `x` to `weave` and update all imports
* Make a new packages `coins` with `coin.go`, `coins.go` etc and treat that as a library package like `crypto` and `errors`
* Totally rethink how we handle imports

*Conclusion* I put everything in the `coin` package and changed tons of imports...

### CODE REVIEW

**Comment by ruseinov** [comment]
@ethanfrey in my opinion best way to resolve it is to implement getter methods for whatever is needed and pass an interface to deliver instead of x.Coin directly.

Then the deliver result won't care about the actual type and we can still get the juice.

And yeah, in concrete decorator we can cast the type.

**Comment by ethanfrey** [comment]
The point is we need to get and set this in many places....

And I can't even define

```golang
type interface Getter {
  GetFee() x.Coin
}
```

due to the imports... I really want to set a coin on it, but it currently cannot know what a coin is...

pulling out coins in a PR now

**Comment by ruseinov** [comment]
I mean, why can't this be an interface{} or a type that implements some methods, like GetWhole() GetFractional() GetTicker() and then you can cast it in some other places you need to.

could be a Currency interface or something

**Comment by husio** [comment]
Now that the package for holding coins is called `coin`, structure names `Coin` and `Coins` could be renamed as well. When used it is now `func x(amount coin.Coin)` or `func x(amount coin.Coins)`. The repetetivnes is weird. This is not an important change but the right renaming could make it look nicer :nail_care: 

I cannot propose anything better although my thinking goes in the direction of something like
```go
func x(amount coin.Coin) {} // now, a single ticker value
func x(amount coin.One) {} // after renaming

func x(amount coin.Coins) {} // now, multiple ticker values
func x(amount coin.Multiple) {} // after renaming
```

**Comment by ethanfrey** [comment]
I will update docs. And yes, let's make a new issue for coin package cleanup.

I just pulled it out into a package to compile properly. Would like more input before renaming everything.

**Comment by ethanfrey** [comment]
About renaming, this breaks lots of protobuf definitions.

I would almost prefer to keep Coin and Coins, but the other functions can easily be renamed. And also, the package could have another name easily

**Pull request merged**
