### PR TITLE
adjust protoc execution to work with Go modules

### LINKED ISSUE #568: Support Go modules: fix protobuf imports
**Is your feature request related to a problem? Please describe.**
With the recent introduction of Go modules the project must not live within the Gopath anymore.
> As of Go 1.11, the go command enables the use of modules when the current directory or any parent directory has a go.mod, provided the directory is outside $GOPATH/src. (Inside $GOPATH/src, for compatibility, the go command still runs in the old GOPATH mode, even if a go.mod is found.

https://blog.golang.org/using-go-modules

While the Go code in the project works outside the GOPATH now the protobuf generation does not as files are depending on parent path structures.

**Describe the solution you'd like**
Make it fully work outside GOPATH as intended by the modules designers

**Describe alternatives you've considered**
-
**Additional context**
`go list -f '{{ .Dir }}' -m github.com/golang/protobuf` may become helpful to set a proper imports in the makefile. See https://www.reddit.com/r/golang/comments/9blgn0/using_go_modules_with_vendorprovided_protobuf/

### PR DESCRIPTION
**Pull request by husio**
This is a draft as there are few tasks to be completed before merging.

We no longer use `GOPATH` and `dep` for dependency management. Using Go
modules requires changes to how protobuf files are declared and
included.

- `protofmt` command no longer works as it does not accept `-I` flag
- `protodoc` is disabled for now as it requires a single protobuf. This
   is waiting for https://github.com/iov-one/weave/pull/659
- some packages cannot be compiled unless weave top level `codec.proto`
  is included. Compiler is printing a warning that this file is not
  used, but it does not compile without it. Weird.

fix #568

### CODE REVIEW

**Comment by ethanfrey** [comment]
Note this in https://github.com/iov-one/weave/blob/master/prototool.yaml

```toml
  # Additional paths to include with -I to protoc.
  # By default, the directory of the config file is included,
  # or the current directory if there is no config file.
  includes:
    - .
    - ./vendor
    - ../../..
```

I'm looking to see how to configure this via cli or environment, but this is where you can pass the -I info down the chain

**Comment by ethanfrey** [comment]
Looking here I also noticed:
```
  # The Protobuf version to use from https://github.com/protocolbuffers/protobuf/releases.
  # By default use 3.6.1.
  # You probably want to set this to make your builds completely reproducible.
  version: 3.6.1
```

While we install v3.7.0 via the Makefile (`make /usr/local/bin/protoc`)

**Comment by husio** [comment]
I have just found out on the prototool page that it does not play well with the long names as well. https://github.com/uber/prototool#tips-and-tricks

**Comment by ethanfrey** [comment]
Running `make protoc` prints out some interesting errors
like `vendor/github.com/tendermint/tendermint/abci/types/types.proto: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.`

Please exclude `./vendor` from the find (maybe this goes away when we no longer use current vendor based tools approach, but nice for safety and for the transition)

**Comment by ethanfrey** [comment]
Also, lines like this seem to be odd:
But is this what you meant by "doesn't compile without reference to codec.proto" (eg self-reference)

https://github.com/iov-one/weave/blob/574c91924ee268c2f6def1986fe31acd2f744e01/cmd/bnsd/app/codec.proto#L6-L7

**Comment by ethanfrey** [comment]
> I have just found out on the prototool page that it does not play well with the long names as well. https://github.com/uber/prototool#tips-and-tricks

Two of those three tips are against our attempts to vendor...
But... do we need to vendor gogoproto for `prototool`? Or just for `protoc`?

**Comment by ethanfrey** [comment]
Maybe this is a good config to use as reference: https://github.com/QubitProducts/iris/blob/master/prototool.yaml

Or we just use prototool in a docker container. And save a whole lot of headaches. We can fork the docker container and set the versions inside to anything we want. But don't worry about having to build protobuf with the same source/deps as the actual running code. Maybe we just use protoc in docker as well...
https://github.com/charithe/prototool-docker

**Comment by ethanfrey** [comment]
If I remove the `protoc.includes` directives from prototool.yaml, this works fine:

```shell
USER="$(id -u):$(id -g)"
docker run -it --rm --user $USER --mount type=bind,source="$(pwd)",target=/work --tmpfs /tmp:exec charithe/prototool-docker prototool format /work/codec.proto
```

**Comment by ethanfrey** [comment]
Very interesting...

`docker run -it --rm --user $USER --mount type=bind,source="$(pwd)",target=/work --tmpfs /tmp:exec charithe/prototool-docker prototool compile --dry-run /work/codec.proto`
will show the paths that it would compile

`docker run -it --rm --user $USER --mount type=bind,source="$(pwd)",target=/work --tmpfs /tmp:exec charithe/prototool-docker prototool generate /work`
should compile them all.

We can just make sure our prototool.yaml is set up well, and run all the scripts from the docker image, and I think this will save a whole lot of nightmares with protoc setup and tool configurations.

**Comment by husio** [comment]
@ethanfrey this can be closed, because your approach is working, correct?

**Comment by ethanfrey** [comment]
Yes, protoc and prototools now work in docker.

**Pull request closed without merging**
