### PR TITLE
Add First() and Last() to KVStore

### PR DESCRIPTION
**Pull request by ethanfrey**
We have an Iterator on KVStore, but it is greedy, and reads all data in the range before returning a value. This is hard to adjust, but for some cases (see below), we only want the first or last item in a range. I add First() and Last() methods to return this one point efficiently.

Using auto-increment ids, we could take the bucket prefix, and call
`db.Last(store.PrefixToRange(bucketPrefix))` and get the most recently added item. 
This will allow us to easily implement queues, such as needed for IBC

For the tutorial, we want to find the open order with the lowest price. We store them indexed by price, but that only works for exact matches. We could create an Iterator over the index and then take the first item as a match. However, that will read in all Orders in the OrderBook. Allowing to quickly get the first/last in a range of data (both for keys and meaningful index) could help here.

Even if you don't fully understand the why, I would like a review that it is correct. There is one point with handling deleted items that still confuses me.

### CODE REVIEW

**Comment by ruseinov** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/iov-one/weave/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ruseinov** [comment]
The idea and purpose are clear, will review the concrete impl tomorrow.

**Comment by husio** [comment]
I am afraid I do not really understand the implementation. It relies heavily on external libraries that I don't know. 
I have a question about the design though.

> We have an Iterator on KVStore, but it is greedy, and reads all data in the range before returning a value. [...] I add First() and Last() methods to return this one point efficiently.

I am guessing that there is a reason preventing us from making the iterator a real iterator and be lazy. Is that correct? Otherwise I think fixing existing implementation is the way to Go. :drum: 

Having a lazy iterator, the database interface would stay small and we avoid introducing different ways of achieving the same result.
If worth it, for convinience the `First` and `Last` could become a functions taking an iterator interface.
```go
k, v, err := store.First(db.Iterator(start, end))
k, v, err := store.Last(db.Iterator(start, end))
```

**Comment by ethanfrey** [comment]
Closing in favor of #762

**Pull request closed without merging**
