### PR TITLE
x/msgfee: add message to change the message fee value

### PR DESCRIPTION
**Pull request by husio**
`x/msgfee` was extended to provide a message to set a fee for a given
message path. Use zero value amount to delete a fee. Transaction for
setting a message fee must be signed by the fee administrator.
Fee administrator is set in the `x/msgfee` configuration, using gconf
and should be initialized with the genesis file.

The messsage fee setting message was added to `bnsd` and `bnscli`.

### CODE REVIEW

**Comment by husio** [comment]
The build is failing with a mysterious 

>     cmd_sigs_test.go:34: transaction signing failed: cannot fetch genesis: cannot fetch: Get http://localhost:44444/genesis: dial tcp 127.0.0.1:44444: connect: connection refused

:sob:

**Comment by ruseinov** [comment]
I have played around with various solutions to this problem and it seems that this is a travis issue after all.

It didn't seem to pop up in any other PRs, but I can see no reason for it to be popping up here either :/

**Comment by ruseinov** [comment]
some insights here: https://github.com/iov-one/weave/pull/996

**Comment by ruseinov** [comment]
@husio basically the problem was that cleanups were not called properly and therefore the next test would try to build to the a busy port.

Now cleanups are being called in a defer after running each test so we have a proper shutdown before running the next one.

**Pull request merged**
