### PR TITLE
Escrow cleanup

### PR DESCRIPTION
**Pull request by alpe**
## Breaking changes:
* Rename `sender` in `createEscrowMsg` to `src`
* Rename `pubKey` in `sigs` to `publicKey`
* Rename `pubKey` in `SetValidatorsMsg`.`Validator` to `publicKey`

Closes https://github.com/iov-one/bcp-demo/issues/30

### CODE REVIEW

**Comment by ethanfrey** [comment]
Sure. I would say it is fine, except the previous request by @Isabello 
> Rename pubKey in sigs to publicKey
may no longer be valid. If we are standardizing on pubkey in iov-core, we should do the same in protobuf definitions (note this is `pubkey` not `pubKey`)

See https://internetofvalues.slack.com/archives/CB0ST6F0W/p1539697481000100

Simon [3:44 PM]
I would like to name public key and private key consistently “pubkey” and “privkey” in IOV-Core. I know those words are not in the dictionary but making them atomic words simplifies code and interfaces by 1. having shorter symbols, 2. having less word separators. Are there any objection against the words “pubkey” and “privkey” in our context?

Isabella Dell [3:46 PM]
i use `pubKey` in my docs
but i can change, im happy with both versions (edited)

Simon [3:49 PM]
My crypto experience says: go for “pubkey” like “dog” or “startup” (edited)

Isabella Dell [3:49 PM]
im down with it

Ethan Frey [3:53 PM]
I think they just updated weave to use publicKey not pubKey

**Comment by alpe** [comment]
I have reverted 446d8adb550a0ac219790aaa0a3249e6a393afca to stay with pubKey

**Comment by Isabello** [comment]
We settled on `pubkey` all lowercase in `iov-core`

**Comment by ethanfrey** [comment]
I think this is good to merge with just changing the `pub_key` fields in the protobuf to `pubkey` (and fixing all code that uses this).

**Pull request merged**
