### PR TITLE
[DEMO: don't merge] Trial kvstore interface cleanup

### LINKED ISSUE #823: Clean up store interface
**Is your feature request related to a problem? Please describe.**

There have been some comments that this could be done better. It was one of the first APIs in weave, and we have learned a lot since then. I'm sure we can improve it.

For example, we now have a much simpler Iterator
```go
type Iterator interface {
	Next() (key, value []byte, err error)
	Release()
}
```

Let us consider the following interfaces here:

```go
type ReadOnlyKVStore interface {
	Get(key []byte) ([]byte, error)
	Has(key []byte) (bool, error)
	Iterator(start, end []byte) (Iterator, error)
	ReverseIterator(start, end []byte) (Iterator, error)
}

type SetDeleter interface {
	Set(key, value []byte) error
	Delete(key []byte) error
}

// Batch is used to cache writes before commiting to a lower store
type Batch interface {
	SetDeleter
	Write() error
}

type KVStore interface {
	ReadOnlyKVStore
	SetDeleter
	NewBatch() Batch
}

type CacheableKVStore interface {
	KVStore
	CacheWrap() KVCacheWrap
}

type KVCacheWrap interface {
	// CacheableKVStore allows us to use this Cache recursively
	CacheableKVStore
	Write() error
	Discard()
}
```

**Describe the solution you'd like**

Some thoughts on cleanup:

* Can we remove `NewBatch()` from `KVStore`? What was my thinking there?
* Can we simplify/unify `CacheableKVStore` and `KVCacheWrap`?
* Can we combine/improve `Iterator` and `ReverseIterator`?

**Describe alternatives you've considered**

One concrete suggestion is to make iterator take functional parameters

```go
// default -> ascending and no limit
type IterConfig struct {
  Descending bool
  Limit int
}

type IterOpt func(IterConfig) IterConfig

type ReadOnlyKVStore interface {
    Iterate(start, end []byte, opts ...IterOpt) (Iterator, error)
}

// example opt we expose
var Reverse IterOpt = func (cfg IterConfig) IterConfig {
  cfg.Descending = true
  return cfg
}
```

**Additional context**

### PR DESCRIPTION
**Pull request by ethanfrey**
Closes #823 

Modify the interfaces as discussed in issue. And update `./store` to use the new interface.

All other code, like Buckets, is not updated yet. Waiting for feedback if to continue with this or change course

### CODE REVIEW

**Comment by iov-bot-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/iov-one/weave/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ethanfrey** [comment]
> All database methods are accepting context, but I don't think they fully support it as they do not check the cancellation status. Usually the database driver should do this work. In our case the database is not context aware.

This makes sense.  I think there is no cancel in iavl, except for the long-running processes, which we do handle with a context.  That said, I like your idea of manually checking cancel in the beginning, so it does have some effect (even if it doesn't abort in middle of the I/O, it will break out long-running processes, like with a  timeout)

**Comment by ruseinov** [comment]
Change seems good to me, and it would indeed be cool to have methods exit on context cancellation, effectively making them a noop if they were just called.

**Comment by husio** [comment]
I would love to merge this. There are a lot of conflicts by now. I can resolve all conflicts and bring the code to mergable state.
Do we want to apply this change? If yes, I can take care of finishing this pull request.

**Comment by ruseinov** [comment]
It does not seem like a good idea to do merge this now as we have decided to hold off on any interface breaking changes that touch multiple packages.

We either have to give up on the idea of keeping master launch-compatible, which in my opinion is an okay approach, or keep this open till we have a way forward. 

To make this decision we'll need to have some direction from business.

**Comment by ethanfrey** [comment]
I think this should be done as a post-launch overhaul. It changes code, but doesn't break any external guarantees (how blockchain txs execute). So easy enough to add in an iov chain upgrade, say 1.0 -> 1.1

**Pull request closed without merging**
