### PR TITLE
bnsd: add validate command for validating genesis

### LINKED ISSUE #658: Some way to validate a genesis file
**Is your feature request related to a problem? Please describe.**
There is no other way currently to validate a genesis file other than to setup a Tendermint + Bnsd. 

**Describe the solution you'd like**
A CLI parameter with the bnsd command would be great

**Describe alternatives you've considered**
* Hosted validation as a service where I can paste my genesis file into and get back any errors as list.
* Separate linter CLI tool

**Additional context**
This would benefit from mulitierr so that I can get a list of errors rather than a single one with each run

### PR DESCRIPTION
**Pull request by husio**
This change introduce a new `bnsd` command - `validate`. It reads a
genesis file under provided path and use application initializers chain
to load genesis declarations into a in-memory store. This functionality
allows for validating genesis state initialization configuration without
the need of running a tendermint server and without creating any files.

Error reporting can be further improved. Currently returned
initialization errors are often times providing only a very enigmatic
error description without any context information.

resolve #658

Example error output:
```
weave $ cmd/bnsd/bnsd validate /tmp/genesis.json
Error: 
github.com/iov-one/weave.ParseAddress
        /home/piotr/weave/conditions.go:171
github.com/iov-one/weave.(*Address).UnmarshalJSON
        /home/piotr/weave/conditions.go:143
encoding/json.(*decodeState).literalStore
        /home/piotr/.go_1.12.5/src/encoding/json/decode.go:855
encoding/json.(*decodeState).value
        /home/piotr/.go_1.12.5/src/encoding/json/decode.go:395
encoding/json.(*decodeState).object
        /home/piotr/.go_1.12.5/src/encoding/json/decode.go:763
encoding/json.(*decodeState).value
        /home/piotr/.go_1.12.5/src/encoding/json/decode.go:381
encoding/json.(*decodeState).array
        /home/piotr/.go_1.12.5/src/encoding/json/decode.go:560
encoding/json.(*decodeState).value
        /home/piotr/.go_1.12.5/src/encoding/json/decode.go:371
encoding/json.(*decodeState).unmarshal
        /home/piotr/.go_1.12.5/src/encoding/json/decode.go:179
encoding/json.Unmarshal
        /home/piotr/.go_1.12.5/src/encoding/json/decode.go:106
github.com/iov-one/weave.Options.ReadOptions
        /home/piotr/weave/handler.go:60
github.com/iov-one/weave/cmd/bnsd/x/username.(*Initializer).FromGenesis
        /home/piotr/weave/cmd/bnsd/x/username/init.go:23
github.com/iov-one/weave/app.chainInitializer.FromGenesis
        /home/piotr/weave/app/genesis.go:23
github.com/iov-one/weave/commands/server.validateGenesis
        /home/piotr/weave/commands/server/validate.go:38
github.com/iov-one/weave/commands/server.ValidateGenesis
        /home/piotr/weave/commands/server/validate.go:15
main.main
        /home/piotr/weave/cmd/bnsd/main.go:75
/tmp/genesis.json: cannot initialize from genesis: initializer "github.com/iov-one/weave/cmd/bnsd/x/username": cannot load username tokens: cannot decode hex: encoding/hex: invalid byte: U+0078 'x'

bnsd
          Blockchain Name Service node

help      Print this message
init      Initialize app options in genesis file
start     Run the abci server
getblock  Extract a block from blockchain.db
retry     Run last block again to ensure it produces same result
validate  Parse given genesis file and ensure that defined there state can be loaded.
version   Print the app version

  -home string
        directory to store files under (default "$HOME/.bns")
```

```
weave $ cmd/bnsd/bnsd validate /tmp/genesis.json
Error: 
github.com/iov-one/weave/x/cash.Initializer.FromGenesis
        /home/piotr/weave/x/cash/init.go:27
github.com/iov-one/weave/app.chainInitializer.FromGenesis
        /home/piotr/weave/app/genesis.go:23
github.com/iov-one/weave/commands/server.validateGenesis
        /home/piotr/weave/commands/server/validate.go:38
github.com/iov-one/weave/commands/server.ValidateGenesis
        /home/piotr/weave/commands/server/validate.go:15
main.main
        /home/piotr/weave/cmd/bnsd/main.go:75
/tmp/genesis.json: cannot initialize from genesis: initializer "github.com/iov-one/weave/x/cash": read cash attribute: invalid format

bnsd
          Blockchain Name Service node

help      Print this message
init      Initialize app options in genesis file
start     Run the abci server
getblock  Extract a block from blockchain.db
retry     Run last block again to ensure it produces same result
validate  Parse given genesis file and ensure that defined there state can be loaded.
version   Print the app version

  -home string
        directory to store files under (default "$HOME/.bns")
```

### CODE REVIEW

**Comment by iov-bot-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/iov-one/weave/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ruseinov** [comment]
It seems like there's something wrong with the output - we can still see the block with available commands:
```
bnsd
          Blockchain Name Service node

help      Print this message
init      Initialize app options in genesis file
start     Run the abci server
getblock  Extract a block from blockchain.db
retry     Run last block again to ensure it produces same result
validate  Parse given genesis file and ensure that defined there state can be loaded.
version   Print the app version

  -home string
        directory to store files under (default "$HOME/.bns")
```

**Comment by ruseinov** [comment]
I think this looks good for an initial version.
It would be interesting to see how this outputs errors for several initialisers (or all of them).
It would also be nice to have some clear separators between errors reported for different initialisers.

**Comment by husio** [comment]
I have updated how the error message is printed and how the help text is build.

**Comment by alpe** [comment]
A good start but this does not report a missing migration config. That was the problem with the last testnet so we should have it covered

**Comment by husio** [comment]
I cannot think of any reasonable way to discover missing migration. We do not register extensions nor the extensions register the use of migration anywhere. This makes it impossible to make this check in an automatic fashion. 
The only solution I can think of is to write in code the list of extensions that migration must be initialized in the genesis. Doing this would make the whole requirement of registering a migration via genesis pointless.

**Comment by alpe** [comment]
The problem with the migrations is very critical as we learned with the previous testnet.

> Doing this would make the whole requirement of registering a migration via genesis pointless.

Can you elaborate why this was configured in the genesis in the first place instead of code or a noop default for version 1?

**Comment by husio** [comment]
> Can you elaborate why this was configured in the genesis in the first place instead of code or a noop default for version 1?

If I remember correctly, this was because we may want to initialize the network with version higher than 1, if we initialize a hard fork. I do not remember why we did not default initialization to 1 and allow to bump it higher, but I think there was a reason for this as well.

**Comment by husio** [comment]
This does not solve the problem.

**Comment by husio** [comment]
Closing as this does not solve the problem. This is not required for the release.
[A new issue will be created](https://github.com/iov-one/weave/issues/948) to describe the problem once more.

**Pull request closed without merging**
