### PR TITLE
Replay tool

### PR DESCRIPTION
**Pull request by ethanfrey**
Note: this is currently forked from 0.11.1 tag to ensure complete compatibility with the test case that failed.

Adds two new subcommands to `bnsd` to support forensic work:

* `bnsd getblock <file> [-height=H]` will extract a json block from a blockstore.db
* `bnsd retry <abci.db> <block.json>` will rollback the database one step and run the last block again. Multiple runs can detect non-determinism

### CODE REVIEW

**Comment by ethanfrey** [comment]
To see this at work, compile bnsd from this branch, download (and unzip) the attached files into the current directory, and run:

`bnsd retry ./bns-d.db block.190258.json -error`

It may run a few times until the output hash is different than the input. Run again and see it switch back.

This captures what killed hugnet.

Happy for someone to add detailed debug logging, or I will do that shortly.
[block.190258.json.zip](https://github.com/iov-one/weave/files/2864561/block.190258.json.zip)
[bns-d.db.zip](https://github.com/iov-one/weave/files/2864562/bns-d.db.zip)

**Comment by ethanfrey** [comment]
Here is an output with some temporary debug info to capture the write order on the underlying iavl tree:

Run 1:
```
$ bnsd retry ./bns-d.db block.190258.json -error
--> Loading Block
--> Loading Database
Original Height: 190258
Original Hash: 96AAD58DBDF2BA87D90BE1F620E80AC3D1662B5113A7667B51303596163A5969
Rollback to height: 190257
---> Begin Block
---> Deliver Tx 0
I[2019-02-14|11:42:54.253]                                              module=bns call=deliver_tx path=nft/username/issue duration=2362
---> End Block
* SET: [736967733A57A332C8A4780B12AF79C190C9C03C833D583148]
* SET: [5F692E7573726E66745F636861696E616464723A74696F76313237336E396A39793071393339746D65637867766E73707573763734737632676A77687736713B626E732D6875676E6574]
* SET: [5F692E7573726E66745F636861696E616464723A323938303033333936323232393433393635304C3B64613365643661343534323932373862616332363636393631323839636131376164383635393564333362333130333736313564346238653866313538626261]
* SET: [5F692E7573726E66745F636861696E616464723A74696F76316A7A78336A737579687576386378647577706B763233396B396463617632303674756479376A3B626F762D6875676E6574]
* SET: [5F692E7573726E66745F6F776E65723A57A332C8A4780B12AF79C190C9C03C833D583148]
* SET: [7573726E66743A6C635F7465737432]
D[2019-02-14|11:42:54.255] Commit synced                                module=bns height=190258 hash=56E581EBD9C0A3D726A91579839F7FF8A9251BEB063FDF0FA0415A0B3429DF6E
Recomputed Hash: 56E581EBD9C0A3D726A91579839F7FF8A9251BEB063FDF0FA0415A0B3429DF6E
```

Run 2:
```
$ bnsd retry ./bns-d.db block.190258.json
--> Loading Block
--> Loading Database
Original Height: 190258
Original Hash: 56E581EBD9C0A3D726A91579839F7FF8A9251BEB063FDF0FA0415A0B3429DF6E
Rollback to height: 190257
---> Begin Block
---> Deliver Tx 0
I[2019-02-14|11:43:02.809]                                              module=bns call=deliver_tx path=nft/username/issue duration=2871
---> End Block
* SET: [736967733A57A332C8A4780B12AF79C190C9C03C833D583148]
* SET: [5F692E7573726E66745F6F776E65723A57A332C8A4780B12AF79C190C9C03C833D583148]
* SET: [5F692E7573726E66745F636861696E616464723A74696F76313237336E396A39793071393339746D65637867766E73707573763734737632676A77687736713B626E732D6875676E6574]
* SET: [5F692E7573726E66745F636861696E616464723A323938303033333936323232393433393635304C3B64613365643661343534323932373862616332363636393631323839636131376164383635393564333362333130333736313564346238653866313538626261]
* SET: [5F692E7573726E66745F636861696E616464723A74696F76316A7A78336A737579687576386378647577706B763233396B396463617632303674756479376A3B626F762D6875676E6574]
* SET: [7573726E66743A6C635F7465737432]
D[2019-02-14|11:43:02.811] Commit synced                                module=bns height=190258 hash=96AAD58DBDF2BA87D90BE1F620E80AC3D1662B5113A7667B51303596163A5969
Recomputed Hash: 96AAD58DBDF2BA87D90BE1F620E80AC3D1662B5113A7667B51303596163A5969
```

Notice the second SET call is already in a different order.

**Comment by ethanfrey** [comment]
Parsing out the keys (the four in the middle that are in different orders), we get:

Run 1:
```
'_i.usrnft_chainaddr:tiov1273n9j9y0q939tmecxgvnspusv74sv2gjwhw6q;bns-hugnet'
'_i.usrnft_chainaddr:2980033962229439650L;da3ed6a45429278bac2666961289ca17ad86595d33b31037615d4b8e8f158bba'
'_i.usrnft_chainaddr:tiov1jzx3jsuyhuv8cxduwpkv239k9dcav206tudy7j;bov-hugnet'
'_i.usrnft_owner:W\xa32\xc8\xa4x\x0b\x12\xafy\xc1\x90\xc9\xc0<\x83=X1H'
```

Run 2:
```
'_i.usrnft_owner:W\xa32\xc8\xa4x\x0b\x12\xafy\xc1\x90\xc9\xc0<\x83=X1H'
'_i.usrnft_chainaddr:tiov1273n9j9y0q939tmecxgvnspusv74sv2gjwhw6q;bns-hugnet'
'_i.usrnft_chainaddr:2980033962229439650L;da3ed6a45429278bac2666961289ca17ad86595d33b31037615d4b8e8f158bba'
'_i.usrnft_chainaddr:tiov1jzx3jsuyhuv8cxduwpkv239k9dcav206tudy7j;bov-hugnet'
```

So, the *order* of updating *indexes* is non-deteministic

**Comment by ethanfrey** [comment]
And [here is the map](https://github.com/iov-one/weave/blob/master/orm/bucket.go#L46)

And [the buggy loop over the map](https://github.com/iov-one/weave/blob/master/orm/bucket.go#L186-L191)

**Comment by ethanfrey** [comment]
I will fix it this afternoon

**Comment by ruseinov** [comment]
@ethanfrey I suppose it can be fixed by storing all the map keys in an ordered array and iterating these keys via an array.
Looks good!

**Comment by ethanfrey** [comment]
So, I captured the issue with a unit test, and fixed the unit test in the next commit, using a sorted list of index rather than a map (amazing this didn't show up for 10 months)

I then rebuilt bnsd and ran `bns retry -error -max=1000` on the same test case, producing a consistently stable app hash after 1000 runs. I think we have fixed the error.

I would like to tag this as a v0.11.2 release and deploy immediately to hugnet to have stability. Then merge it into master (which has other changes maybe not ready for release).

**Pull request merged**
