### PR TITLE
remove gov.TallyMsg handler

### PR DESCRIPTION
**Pull request by husio**
Remove `gov.TallyMsg` handler from message router. Provide a custom
router for the cron handler and register mostly necessary handler,
inlcuding `gov.TallyMsg` handler.

Tests are ~not~ updated.

@alpe I have removed the handler as requested, and I am not sure if this change is worth it. This is quite a big change and customization for a very little gain.
Let me know what you think. If you say the gain is worth it then I will update the tests and let's merge it. Otherwise, we can drop this pull request and the idea.

### CODE REVIEW

**Comment by iov-bot-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/iov-one/weave/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by husio** [comment]
I have force pushed a change, so that it's all in a single commit.

In addition to previous changes, I have only updated the tests and the changelog.

**Comment by ruseinov** [comment]
LGTM when the tests pass.

**Comment by husio** [comment]
> What about removing bnsd.Tx.gov_tally_msg? Do we need internal messages in this list?

Great catch! I completely forgot about it.

**Pull request merged**
