### PR TITLE
x/username: change address type from []byte to string

### LINKED ISSUE #860: Consistent Username addresses encoding
**Is your feature request related to a problem? Please describe.**
We use hex encoding with our weave addresses but current initializer code expectes base64 encoded (json default) addresses. 

**Describe the solution you'd like**
hex encoding

**Describe alternatives you've considered**
Not enforcing a chain address for a username in genesis would actually be better for my case.

**Additional context**
See https://github.com/iov-one/weave/issues/848

### PR DESCRIPTION
**Pull request by husio**
Instead of storing user address as bytes, use string type. This means
that instead of base64 encoded value we use the string representation of
an address everywhere.
While less compact, using string representation is easier to work with.

@webmaster128 I think you will be happy to see this merged.

resolve #860

### CODE REVIEW

**Comment by ruseinov** [comment]
> Change is nice, but you deleted all the `spec/testvectors`. This should be properly updated during `make protoc`. Can you run `make testvectors` and see what happens?

Happened to me a lot when making changes to codecs, as basically if running bnsd command fails for some reason - we're left without testvectors. Just gotta be mindful of a bunch of deleted files in `git status`, but I keep wondering if there is a better way of doing this to avoid these issues.

**Comment by husio** [comment]
@ethanfrey good catch!

I think this happened because `make protoc` is trying to execute Go code. To be more precise, `make testvectors` is running `bnsd` which cannot compile because the types were changed.

**Comment by webmaster128** [comment]
Nice. This closes https://github.com/iov-one/weave/issues/848 as well, right?

**Comment by husio** [comment]
Now I wonder if what I have implemented here is what was intended. It would be weird to have two issues for the very same change. 
@alpe can you confirm?

**Comment by ethanfrey** [comment]
> I think this happened because make protoc is trying to execute Go code. To be more precise, make testvectors is running bnsd which cannot compile because the types were changed.

This is why it is at the end... after all protoc compilation. I put it there to avoid exactly this compile failure. Please try it again and let me know how it runs (paste error message here)

**Comment by ethanfrey** [comment]
I think #860 (use hex encoded binary) can be closed in favor of #848 (use string).

And this PR really closes #848 not #860

**Pull request merged**
